-- ============================================================
-- Carrier Dispatch Express — Supabase Schema
-- Three-step rule: CREATE → ENABLE RLS → GRANT (on every table)
-- GRANT required: tables invisible without it after Oct 30 2026
-- (select auth.uid()) not auth.uid() — prevents performance death
-- USING + WITH CHECK on every UPDATE policy
-- security_invoker = true on every view
-- ============================================================

-- ─── Extensions ──────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── Enums ───────────────────────────────────────────────────────────────────

CREATE TYPE user_role AS ENUM (
  'professional_athlete', 'college_athlete', 'agent',
  'team_staff', 'nil_collective', 'admin'
);

CREATE TYPE booking_model AS ENUM ('full_service', 'marketplace');

CREATE TYPE service_tier AS ENUM ('standard', 'priority', 'white_glove');

CREATE TYPE shipment_status AS ENUM (
  'pending', 'quoted', 'accepted', 'assigned',
  'picked_up', 'in_transit', 'delivered', 'cancelled', 'disputed'
);

CREATE TYPE quote_status AS ENUM (
  'pending', 'accepted', 'rejected', 'countered', 'expired'
);

CREATE TYPE payment_status AS ENUM (
  'pending', 'authorized', 'captured', 'refunded', 'failed'
);

CREATE TYPE notif_channel AS ENUM ('sms', 'email', 'push');

CREATE TYPE audit_action AS ENUM (
  'shipment_created', 'quote_accepted', 'carrier_assigned',
  'payment_captured', 'dispute_opened', 'dispute_resolved',
  'zelle_confirmed', 'status_updated'
);

-- ─── users ───────────────────────────────────────────────────────────────────

CREATE TABLE public.users (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email               TEXT NOT NULL UNIQUE,
  full_name           TEXT NOT NULL,
  role                user_role NOT NULL,
  phone               TEXT,
  avatar_url          TEXT,
  stripe_customer_id  TEXT,
  hubspot_contact_id  TEXT,
  is_active           BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.users TO authenticated;

-- Policies: users see + edit only their own row; admins see all
CREATE POLICY "users_select_own"
  ON public.users FOR SELECT
  USING ((select auth.uid()) = id);

CREATE POLICY "users_update_own"
  ON public.users FOR UPDATE
  USING ((select auth.uid()) = id)
  WITH CHECK ((select auth.uid()) = id);

CREATE POLICY "admin_select_all_users"
  ON public.users FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

-- ─── vehicles ────────────────────────────────────────────────────────────────

CREATE TABLE public.vehicles (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  make          TEXT NOT NULL,
  model         TEXT NOT NULL,
  year          INTEGER NOT NULL,
  -- vehicle_type must be one of the 19 Super Dispatch enum values
  -- "car" returns HTTP 400 — enforced structurally by TypeScript, backed here
  vehicle_type  TEXT NOT NULL CHECK (vehicle_type IN (
    'sedan', '2_door_coupe', 'suv', 'pickup', '4_door_pickup',
    'van', 'truck_daycab', 'truck_sleeper', 'motorcycle', 'boat',
    'rv', 'heavy_machinery', 'freight', 'livestock', 'atv',
    'trailer_bumper_pull', 'trailer_gooseneck', 'trailer_5th_wheel', 'other'
  )),
  color         TEXT,
  vin           TEXT,
  license_plate TEXT,
  is_inoperable BOOLEAN NOT NULL DEFAULT false,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vehicles TO authenticated;

CREATE POLICY "vehicles_owner_all"
  ON public.vehicles FOR ALL
  USING ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "admin_all_vehicles"
  ON public.vehicles FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

-- ─── shipments ───────────────────────────────────────────────────────────────

CREATE TABLE public.shipments (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- order_guid = critical link: portal (Supabase) ↔ automation (n8n/HubSpot)
  -- UUID generated by portal on creation, sent with every webhook
  order_guid                UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  user_id                   UUID NOT NULL REFERENCES public.users(id),
  vehicle_id                UUID NOT NULL REFERENCES public.vehicles(id),
  booking_model             booking_model NOT NULL,
  service_tier              service_tier NOT NULL DEFAULT 'standard',
  status                    shipment_status NOT NULL DEFAULT 'pending',
  origin_address            TEXT NOT NULL,
  origin_city               TEXT NOT NULL,
  origin_state              TEXT NOT NULL,
  origin_zip                TEXT NOT NULL,
  destination_address       TEXT NOT NULL,
  destination_city          TEXT NOT NULL,
  destination_state         TEXT NOT NULL,
  destination_zip           TEXT NOT NULL,
  pickup_date               DATE,
  delivery_date             DATE,
  estimated_miles           NUMERIC,
  carrier_name              TEXT,
  carrier_id                TEXT,
  super_dispatch_order_id   TEXT,
  hubspot_deal_id           TEXT,
  notes                     TEXT,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.shipments TO authenticated;

CREATE POLICY "shipments_owner_select"
  ON public.shipments FOR SELECT
  USING ((select auth.uid()) = user_id);

CREATE POLICY "shipments_owner_insert"
  ON public.shipments FOR INSERT
  WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "shipments_owner_update"
  ON public.shipments FOR UPDATE
  USING ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "admin_all_shipments"
  ON public.shipments FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

-- Agent sees shipments of athletes they manage (placeholder — expand post-kickoff)
CREATE POLICY "agent_managed_shipments"
  ON public.shipments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role IN ('agent', 'team_staff', 'nil_collective')
    )
  );

-- ─── quotes ──────────────────────────────────────────────────────────────────

CREATE TABLE public.quotes (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shipment_id         UUID NOT NULL REFERENCES public.shipments(id),
  order_guid          UUID NOT NULL,
  -- carrier_pay from SD Pricing Insights API — raw, never touched by LLM
  carrier_pay         NUMERIC,
  -- shipper_quote = Math.round(carrier_pay / (1 - 0.20)) — JS computes
  shipper_quote       NUMERIC,
  market_rate_low     NUMERIC,
  market_rate_high    NUMERIC,
  estimated_miles     NUMERIC,
  currency            TEXT NOT NULL DEFAULT 'USD',
  status              quote_status NOT NULL DEFAULT 'pending',
  expires_at          TIMESTAMPTZ,
  -- MANUAL_REVIEW_REQUIRED | PRICING_API_FAILED | AUTO
  quote_path          TEXT,
  sd_counter_offer_id TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.quotes TO authenticated;

CREATE POLICY "quotes_owner_select"
  ON public.quotes FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.shipments s
      WHERE s.id = quotes.shipment_id AND s.user_id = (select auth.uid())
    )
  );

CREATE POLICY "quotes_owner_update"
  ON public.quotes FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.shipments s
      WHERE s.id = quotes.shipment_id AND s.user_id = (select auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.shipments s
      WHERE s.id = quotes.shipment_id AND s.user_id = (select auth.uid())
    )
  );

CREATE POLICY "admin_all_quotes"
  ON public.quotes FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

-- ─── payments ────────────────────────────────────────────────────────────────

CREATE TABLE public.payments (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shipment_id               UUID NOT NULL REFERENCES public.shipments(id),
  stripe_payment_intent_id  TEXT,
  stripe_event_id           TEXT,
  amount_cents              INTEGER NOT NULL,
  currency                  TEXT NOT NULL DEFAULT 'usd',
  status                    payment_status NOT NULL DEFAULT 'pending',
  -- Military discount = Stripe coupon code, NOT a separate booking flow
  coupon_code               TEXT,
  zelle_confirmed_by        UUID REFERENCES public.users(id),
  zelle_confirmed_at        TIMESTAMPTZ,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.payments TO authenticated;

CREATE POLICY "payments_owner_select"
  ON public.payments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.shipments s
      WHERE s.id = payments.shipment_id AND s.user_id = (select auth.uid())
    )
  );

CREATE POLICY "admin_all_payments"
  ON public.payments FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

-- ─── processed_webhooks (Stripe idempotency) ─────────────────────────────────

CREATE TABLE public.processed_webhooks (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_event_id TEXT NOT NULL UNIQUE,   -- GUID dedup — prevents double invoice
  event_type      TEXT NOT NULL,
  processed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.processed_webhooks ENABLE ROW LEVEL SECURITY;
-- Service role only — no authenticated user access
-- Webhook handler uses createAdminClient() which bypasses RLS
GRANT INSERT, SELECT ON public.processed_webhooks TO service_role;

-- ─── notifications ───────────────────────────────────────────────────────────

CREATE TABLE public.notifications (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  shipment_id UUID REFERENCES public.shipments(id) ON DELETE SET NULL,
  channel     notif_channel NOT NULL,
  subject     TEXT,
  body        TEXT NOT NULL,
  is_read     BOOLEAN NOT NULL DEFAULT false,
  sent_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
GRANT SELECT, UPDATE ON public.notifications TO authenticated;

CREATE POLICY "notifications_owner"
  ON public.notifications FOR SELECT
  USING ((select auth.uid()) = user_id);

CREATE POLICY "notifications_mark_read"
  ON public.notifications FOR UPDATE
  USING ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);

-- ─── audit_log ───────────────────────────────────────────────────────────────

CREATE TABLE public.audit_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shipment_id     UUID REFERENCES public.shipments(id) ON DELETE SET NULL,
  user_id         UUID REFERENCES public.users(id) ON DELETE SET NULL,
  action          audit_action NOT NULL,
  payload         JSONB,
  hubspot_synced  BOOLEAN NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT ON public.audit_log TO authenticated;
GRANT INSERT ON public.audit_log TO service_role;

CREATE POLICY "admin_all_audit"
  ON public.audit_log FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

CREATE POLICY "owner_insert_audit"
  ON public.audit_log FOR INSERT
  WITH CHECK (
    (select auth.uid()) = user_id
  );

-- ─── referral_credits ────────────────────────────────────────────────────────

CREATE TABLE public.referral_credits (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_id   UUID NOT NULL REFERENCES public.users(id),
  referred_id   UUID NOT NULL REFERENCES public.users(id),
  credit_cents  INTEGER NOT NULL DEFAULT 0,
  redeemed      BOOLEAN NOT NULL DEFAULT false,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.referral_credits ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.referral_credits TO authenticated;

CREATE POLICY "referral_credits_owner"
  ON public.referral_credits FOR SELECT
  USING ((select auth.uid()) = referrer_id OR (select auth.uid()) = referred_id);

-- ─── carrier_bids ────────────────────────────────────────────────────────────

CREATE TABLE public.carrier_bids (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shipment_id           UUID NOT NULL REFERENCES public.shipments(id),
  carrier_id            TEXT NOT NULL,
  carrier_name          TEXT NOT NULL,
  bid_amount_cents      INTEGER NOT NULL,
  insurance_amount_cents INTEGER,
  eta_days              INTEGER,
  status                TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.carrier_bids ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.carrier_bids TO authenticated;
GRANT INSERT, UPDATE ON public.carrier_bids TO service_role;

CREATE POLICY "admin_all_bids"
  ON public.carrier_bids FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = (select auth.uid()) AND u.role = 'admin'
    )
  );

CREATE POLICY "owner_select_bids"
  ON public.carrier_bids FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.shipments s
      WHERE s.id = carrier_bids.shipment_id AND s.user_id = (select auth.uid())
    )
  );

-- ─── View: shipment_status_overview ──────────────────────────────────────────
-- security_invoker = true → RLS is enforced through the view.
-- Without this, views bypass RLS by default on Postgres 15+ (Supabase silent failure).

CREATE OR REPLACE VIEW public.shipment_status_overview
WITH (security_invoker = true)
AS
SELECT
  s.id,
  s.order_guid,
  s.status,
  s.service_tier,
  s.booking_model,
  s.user_id,
  s.origin_city,
  s.destination_city,
  s.carrier_name,
  s.created_at
FROM public.shipments s;

GRANT SELECT ON public.shipment_status_overview TO authenticated;

-- ─── Realtime ────────────────────────────────────────────────────────────────
-- Use Postgres Changes (not Broadcast) — Broadcast caused the June 24-25 2026 outage.
-- 30-second fallback polling is baked into the useRealtimeStatus hook.

ALTER publication supabase_realtime ADD TABLE public.shipments;
ALTER publication supabase_realtime ADD TABLE public.notifications;
ALTER publication supabase_realtime ADD TABLE public.quotes;
